const TABLE = [
  // [method, path-regex, handler]
  ["GET",  /^\/healthz\/?$/,                healthz],
  ["GET",  /^\/stocks\/?$/,                  listStocks],
  ["GET",  /^\/stocks\/remove\/?$/,          stub.bind(null, "stocks_remove_list", { hint: "use DELETE/POST /api/stocks/remove/<code>" })],
  ["POST", /^\/stocks\/add\/?$/,             addStock],
  ["GET",  /^\/stock\/?$/,                   stub.bind(null, "stock_index", { hint: "use /api/stock/<ticker>" })],
  ["DELETE", /^\/stocks\/remove\/([^/]+?)\/?$/, removeStock],
  ["POST",    /^\/stocks\/remove\/([^/]+?)\/?$/, removeStock],
  ["GET",   /^\/stock\/([^/]+?)\/?$/,        stockKlines],
  ["GET",   /^\/stock\/([^/]+?)\/etf_membership\/?$/, stockEtfMembership],
  ["GET",   /^\/stock\/([^/]+?)\/events\/?$/,  stockEvents],
  ["GET",   /^\/stock\/([^/]+?)\/intro\/?$/,   stockIntro],
  ["GET",   /^\/index\/([^/]+?)\/?$/,        indexKlines],

  ["GET",  /^\/market_gaps\/?$/,             marketGaps],

  ["GET",  /^\/scan\/?$/,                    scanAll],
  ["POST", /^\/scan\/?$/,                    scanAll],
  ["GET",  /^\/scan_and_email\/?$/,          scanAndEmail],
  ["POST", /^\/scan_and_email\/?$/,          scanAndEmail],

  ["GET",  /^\/fibonacci\/?$/,               stub.bind(null, "fibonacci_index", { hint: "use /api/fibonacci/<code>" })],
  ["GET",  /^\/fibonacci\/([^/]+?)\/?$/,     fibonacciFor],

  ["GET",  /^\/index\/?$/,                   indexEndpoint],
  ["GET",  /^\/institutional\/?$/,           institutional],
  ["GET",  /^\/institutional\/([^/]+?)\/?$/, institutionalByCode],
  ["GET",  /^\/stock_industry\/?$/,          stockIndustry],

  ["GET",  /^\/intraday_scan\/status\/?$/,   intradayScanStatus],
  ["POST", /^\/intraday_scan\/toggle\/?$/,   intradayScanToggle],

  ["GET",  /^\/recipients\/?$/,              listRecipients],
  ["POST", /^\/recipients\/add\/?$/,         addRecipient],
  ["POST", /^\/recipients\/remove\/?$/,      removeRecipient],
  ["GET",  /^\/recipients\/([^/]+?)\/?$/,    recipientById],

  ["GET",  /^\/position_history\/?$/,        positionHistory],

  ["GET",  /^\/macro_news\/?$/,              macroNews],
  ["GET",  /^\/news\/?$/,                    newsList],
  ["GET",  /^\/news\/market\/?$/,            newsMarket],
  ["GET",  /^\/news\/([^/]+?)\/?$/,          newsByCode],
  ["GET",  /^\/macro_data\/?$/,              macroData],
  ["GET",  /^\/macro_yield2y_history\/?$/,   macroYield2yHistory],

  ["POST", /^\/markers\/record\/?$/,         markersRecord],
  ["GET",  /^\/markers\/history\/?$/,        markersHistory],
  ["GET",  /^\/markers\/batch_scan\/?$/,     markersBatchScan],
  ["GET",  /^\/markers\/batch_scan\/status\/?$/, markersBatchScanStatus],
  ["GET",  /^\/markers\/export\.csv\/?$/,    markersExport],
  ["GET",  /^\/markers\/([^/]+?)\/?$/,       markerById],

  ["GET",  /^\/strategy_signals\/?$/,        strategySignals],
  ["GET",  /^\/strategy_signals\/([^/]+?)\/?$/, strategySignals],

  ["GET",  /^\/signal_history\/?$/,          signalHistory],
  ["POST", /^\/signal_history\/record\/?$/,  signalHistoryRecord],

  ["GET",  /^\/warming_zone_scan\/?$/,       warmingZoneScan],
  ["GET",  /^\/warming_zone_scan\/status\/?$/, warmingZoneScanStatus],
  ["GET",  /^\/warming_zone_scan\/refresh\/?$/, warmingZoneScan],

  ["GET",  /^\/signal_filter\/?$/,           signalFilter],
  ["GET",  /^\/signal_filter\/status\/?$/,   signalFilterStatus],
  ["GET",  /^\/signal_filter\/refresh\/?$/,  signalFilter],
  ["GET",  /^\/signal_filter\/all_strategy_hits\/?$/, signalFilter],

  ["GET",  /^\/intraday_check\/?$/,          stub.bind(null, "intraday_check", { hint: "use /api/intraday_check/<code>" })],
  ["GET",  /^\/intraday_check\/([^/]+?)\/?$/, intradayCheck],
  ["GET",  /^\/intraday_check\/status\/?$/,  stub.bind(null, "intraday_check_status", { enabled: false, message: "intraday scan disabled" })],

  // ETF holdings
  ["GET",  /^\/etf_holdings\/snapshot\/?$/,  etfSnapshot],
  ["POST", /^\/etf_holdings\/snapshot_all\/?$/, etfSnapshotAll],
  ["GET",  /^\/etf_holdings\/snapshot_all\/?$/,  etfSnapshotAll],
  ["GET",  /^\/etf_holdings\/snapshot_all\/status\/?$/, etfSnapshotAllStatus],
  ["GET",  /^\/etf_holdings\/status\/?$/,    etfStatus],
  ["GET",  /^\/etf_holdings\/list\/?$/,      etfList],
  ["POST", /^\/etf_holdings\/analyze\/?$/,   etfAnalyze],
  ["GET",  /^\/etf_holdings\/analyze\/?$/,   etfAnalyze],
  ["POST", /^\/etf_holdings\/clear_cache\/?$/, etfClearCache],
  ["GET",  /^\/etf_holdings\/clear_cache\/?$/, etfClearCache],
  ["GET",  /^\/etf_holdings\/pivot\/concentration\/?$/, etfPivotConcentration],
  ["GET",  /^\/etf_holdings\/pivot\/consensus\/?$/, etfPivotConsensus],
  ["GET",  /^\/etf_holdings\/pivot\/weight_matrix\/?$/, etfPivotWeightMatrix],
  ["GET",  /^\/etf_holdings\/pivot\/overlap\/?$/, etfPivotOverlap],
  ["GET",  /^\/etf_holdings\/pivot\/overlap_detail\/([^/]+?)\/([^/]+?)\/?$/, etfPivotOverlapDetail],
  ["GET",  /^\/etf_holdings\/pivot\/time_heatmap\/([^/]+?)\/?$/, etfPivotTimeHeatmap],
  ["GET",  /^\/etf_holdings\/pivot\/turnover\/?$/, etfPivotTurnover],
  ["GET",  /^\/etf_holdings\/snapshots\/([^/]+?)\/?$/, etfSnapshots],
  ["GET",  /^\/etf_holdings\/diff\/([^/]+?)\/?$/, etfDiff],
  ["GET",  /^\/etf_holdings\/export\/([^/]+?)\/?$/, etfExport],
  ["GET",  /^\/etf_holdings\/stock_scan\/status\/([^/]+?)\/?$/, etfStockScanStatus],
  ["POST", /^\/etf_holdings\/stock_scan\/([^/]+?)\/?$/, etfStockScan],
  ["GET",  /^\/etf_holdings\/stock_scan\/([^/]+?)\/?$/, etfStockScan],
  ["GET",  /^\/etf_holdings\/stock_scan\/result\/([^/]+?)\/?$/, etfStockScanResult],
  ["POST", /^\/etf_holdings\/list\/add\/?$/, etfListAdd],
  ["POST", /^\/etf_holdings\/list\/remove\/?$/, etfListRemove],
  ["GET",  /^\/etf_holdings\/([^/]+?)\/?$/,  etfByCode],

  // Rebalance
  ["GET",  /^\/rebalance\/?$/,               rebalanceCompute],
  ["POST", /^\/rebalance\/?$/,               rebalanceCompute],
  ["GET",  /^\/rebalance\/dynamic\/?$/,      rebalanceDynamic],
  ["POST", /^\/rebalance\/dynamic\/?$/,      rebalanceDynamic],
  ["GET",  /^\/rebalance\/groups\/?$/,       rebalanceGroups],

  // Conference / sentiment
  ["GET",  /^\/conference\/?$/,              conferenceList],
  ["GET",  /^\/conference\/sentiment_stats\/?$/, conferenceSentimentStats],
  ["GET",  /^\/conference\/([^/]+?)\/?$/,    conferenceByCode],

  // Uptrend watch
  ["GET",  /^\/uptrend_watch\/?$/,           uptrendWatch],
  ["GET",  /^\/uptrend_watch_filter\/?$/,    uptrendWatchFilter],

  // Admin
  ["GET",  /^\/admin\/logs\/?$/,             adminLogs],
  ["POST", /^\/admin\/logs\/clear\/?$/,      adminLogsClear],
  ["GET",  /^\/admin\/logs\/([^/]+?)\/?$/,   adminLogs],
  ["GET",  /^\/admin\/load\/institutional\/?$/, loadInstitutional],
  ["POST", /^\/admin\/load\/institutional\/?$/, loadInstitutional],
  ["GET",  /^\/admin\/load\/exdiv\/?$/,      loadExdiv],
  ["POST", /^\/admin\/load\/exdiv\/?$/,      loadExdiv],
  ["POST", /^\/admin\/load\/all\/?$/,        loadAll],
  ["GET",  /^\/admin\/load\/revenue\/?$/,    loadRevenue],
  ["POST", /^\/admin\/load\/revenue\/?$/,    loadRevenue],
  ["GET",  /^\/admin\/load\/overseas\/?$/,    loadOverseasIndices],
  ["POST", /^\/admin\/load\/overseas\/?$/,    loadOverseasIndices],
  ["GET",  /^\/admin\/load\/futures\/?$/,     loadFutures],
  ["POST", /^\/admin\/load\/futures\/?$/,     loadFutures],
  ["GET",  /^\/admin\/load\/ai_capex\/?$/,    loadAiCapex],
  ["POST", /^\/admin\/load\/ai_capex\/?$/,    loadAiCapex],
  ["GET",  /^\/admin\/load\/market_prices\/?$/, loadMarketPrices],
  ["POST", /^\/admin\/load\/market_prices\/?$/, loadMarketPrices],
  ["GET",  /^\/admin\/load\/market_prices\/backfill\/?$/, loadMarketPricesBackfill],
  ["POST", /^\/admin\/load\/market_prices\/backfill\/?$/, loadMarketPricesBackfill],
  ["GET",  /^\/admin\/load\/sectors\/?$/,          loadSectors],
  ["POST", /^\/admin\/load\/sectors\/?$/,          loadSectors],
  ["GET",  /^\/admin\/load\/all\/?$/,              loadAllCombined],
  ["POST", /^\/admin\/load\/all\/?$/,              loadAllCombined],
  ["GET",  /^\/admin\/load\/etf_holdings\/?$/,  loadEtfHoldings],
  ["POST", /^\/admin\/load\/etf_holdings\/?$/,  loadEtfHoldings],
  ["GET",  /^\/admin\/load\/macro_yields\/?$/,  loadMacroYields],
  ["POST", /^\/admin\/load\/macro_yields\/?$/,  loadMacroYields],
  ["GET",  /^\/admin\/load\/macro_news\/?$/,    loadMacroNews],
  ["POST", /^\/admin\/load\/macro_news\/?$/,    loadMacroNews],
  ["GET",  /^\/admin\/load\/index_institutional\/?$/, loadIndexInstitutional],
  ["POST", /^\/admin\/load\/index_institutional\/?$/, loadIndexInstitutional],
  ["GET",  /^\/admin\/load\/markers\/?$/,       loadMarkers],
  ["POST", /^\/admin\/load\/markers\/?$/,       loadMarkers],
  ["POST", /^\/admin\/load\/etf_holdings\/seed\/?$/, seedEtfHoldings],
  ["POST", /^\/admin\/load\/big_holders\/seed\/?$/, seedBigHolders],
  ["POST", /^\/admin\/load\/financial_reports\/seed\/?$/, seedFinancialReports],
  ["GET",  /^\/admin\/load\/big_holders\/finmind\/?$/, loadBigHoldersFinMind],
  ["POST", /^\/admin\/load\/big_holders\/finmind\/?$/, loadBigHoldersFinMind],
  ["GET",  /^\/admin\/load\/financial_reports\/finmind\/?$/, loadFinancialReportsFinMind],
  ["POST", /^\/admin\/load\/financial_reports\/finmind\/?$/, loadFinancialReportsFinMind],

  // Ex-dividend (queries real dividend_calendar table)
  ["GET",  /^\/exdiv\/calendar\/?$/,         exdivCalendar],
  ["GET",  /^\/exdiv\/upcoming\/?$/,         exdivUpcoming],

  // Real screener handlers (use etf_watchlist + market_price_bars)
  ["GET",  /^\/etf_signal_filter\/?$/,       etfSignalFilter],
  ["GET",  /^\/etf_signal_filter\/status\/?$/, etfSignalFilterStatus],
  ["GET",  /^\/etf_signal_filter\/refresh\/?$/, etfSignalFilterRefresh],
  ["GET",  /^\/stock_damo_filter\/?$/,       stockDamoFilter],
  ["GET",  /^\/stock_damo_filter\/status\/?$/, stockDamoFilterStatus],
  ["GET",  /^\/stock_damo_filter\/refresh\/?$/, stockDamoFilterRefresh],

  // Real table-backed handlers (will return empty + message when table is empty)
  ["GET",  /^\/foreign_futures\/?$/,         foreignFutures],
  ["GET",  /^\/financial\/?$/,               financial],
  ["GET",  /^\/financial\/([^/]+?)\/?$/,     financial],
  ["GET",  /^\/overnight_signal\/?$/,        overnightSignal],
  ["GET",  /^\/margin_burst\/?$/,            marginBurst],
  ["GET",  /^\/margin_burst\/([^/]+?)\/?$/,  marginBurst],
  ["GET",  /^\/index_institutional\/?$/,     indexInstitutional],
  ["GET",  /^\/big_holder_low_base\/?$/,     bigHolderLowBase],
  ["GET",  /^\/revenue\/?$/,                 revenue],
  ["GET",  /^\/heatmap\/?$/,                 heatmap],
  ["GET",  /^\/price_compare\/?$/,           priceCompare],
  ["GET",  /^\/ai_capex\/?$/,                aiCapex],
  ["GET",  /^\/sold_too_early\/?$/,          soldTooEarly],
  ["GET",  /^\/stock_news_scan\/?$/,         stockNewsScan],
  ["GET",  /^\/stock_news_scan\/quota\/?$/,  stockNewsScanQuota],

  // Configuration endpoints (no DB table — return helpful shape with hint)
  ["GET",  /^\/strategy\/etf_added_resonance\/?$/, placeholder.bind(null, "strategy_etf_added_resonance", "use etf_holdings + screener + resonance score")],
  ["GET",  /^\/disabled_strategies\/?$/,     placeholder.bind(null, "disabled_strategies", "configure in code or DB; returns [] when none disabled")],
  ["GET",  /^\/pe_threshold\/?$/,            peThreshold],
  ["GET",  /^\/min_hold_overrides\/?$/,      placeholder.bind(null, "min_hold_overrides", "per-stock minimum hold days override; empty = use default")],
];
