// api/[...path].mjs — Vercel Serverless Function wrapping the bundled
// Express app. Each incoming request is converted from a Web Request into an
// Node IncomingMessage-shaped object, handed to Express, and the resulting
// ServerResponse is serialized back to a Web Response.
//
// The Express app lives in api/_backend.mjs (generated by api-server-src/build.mjs).
// We import it lazily on first invocation so cold-start cost is paid once
// per serverless instance, not once per request.

import { Readable } from "node:stream";
import { createServer } from "node:http";

let _appPromise = null;
async function getApp() {
  if (!_appPromise) {
    _appPromise = import("./_backend.mjs").then((m) => m.default || m.app);
  }
  return _appPromise;
}

// In-memory response buffer used while Express builds the response.
class ResponseBuffer {
  constructor() {
    this.statusCode = 200;
    this.statusMessage = "OK";
    this.headers = new Map();
    this.bodyChunks = [];
    this.headersSent = false;
  }
  setHeader(name, value) {
    if (this.headersSent) return;
    const v = Array.isArray(value) ? value : [String(value)];
    this.headers.set(name.toLowerCase(), v);
  }
  getHeader(name) {
    const v = this.headers.get(name.toLowerCase());
    return v ? v.join(", ") : undefined;
  }
  removeHeader(name) {
    this.headers.delete(name.toLowerCase());
  }
  writeHead(statusCode, statusMessage, headers) {
    this.statusCode = statusCode;
    if (statusMessage) this.statusMessage = statusMessage;
    if (headers) {
      for (const [k, v] of Object.entries(headers)) this.setHeader(k, v);
    }
    this.headersSent = true;
    return this;
  }
  set(name, value) {
    this.setHeader(name, value);
    return this;
  }
  status(code) {
    this.statusCode = code;
    return this;
  }
  getHeaderNames() {
    return Array.from(this.headers.keys());
  }
  hasHeader(name) {
    return this.headers.has(name.toLowerCase());
  }
  write(chunk) {
    if (chunk) this.bodyChunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
    return true;
  }
  end(chunk) {
    if (chunk && typeof chunk !== "function") {
      this.write(chunk);
    }
    this.headersSent = true;
    this._resolvePromise && this._resolvePromise();
  }
  // Helper used by json/send express methods.
  _finish() {
    if (!this.headersSent) this.headersSent = true;
    this._resolvePromise && this._resolvePromise();
  }
}

// Express helper methods that are missing on our shim but called by the
// route handlers. We install them on each fresh ResponseBuffer instance.
function installExpressHelpers(res) {
  res.json = (body) => {
    res.setHeader("Content-Type", "application/json; charset=utf-8");
    res.write(JSON.stringify(body));
    res._finish();
  };
  res.send = (body) => {
    if (typeof body === "object" && body !== null) {
      res.setHeader("Content-Type", "application/json; charset=utf-8");
      res.write(JSON.stringify(body));
    } else {
      res.setHeader("Content-Type", "text/plain; charset=utf-8");
      res.write(String(body ?? ""));
    }
    res._finish();
  };
  res.sendStatus = (code) => {
    res.statusCode = code;
    res.setHeader("Content-Type", "text/plain; charset=utf-8");
    res.write(require("http").STATUS_CODES[code] || "");
    res._finish();
  };
}

// Convert a Web Request to a Node IncomingMessage-compatible object.
async function webRequestToNode(req) {
  const url = new URL(req.url);
  // Build minimal Node req object
  const headers = {};
  req.headers.forEach((v, k) => {
    headers[k.toLowerCase()] = v;
  });
  const method = req.method;
  let body;
  if (method !== "GET" && method !== "HEAD") {
    body = Buffer.from(await req.arrayBuffer());
  } else {
    body = null;
  }
  // Create a Readable stream that emits the body (or is empty for GET/HEAD).
  const nodeReq = new Readable({
    read() {
      if (body) {
        this.push(body);
      }
      this.push(null);
    },
  });
  nodeReq.method = method;
  nodeReq.url = url.pathname + url.search;
  nodeReq.headers = headers;
  nodeReq.httpVersion = "1.1";
  nodeReq.httpVersionMajor = 1;
  nodeReq.httpVersionMinor = 1;
  nodeReq.connection = { remoteAddress: req.headers.get("x-forwarded-for")?.split(",")[0]?.trim() || "127.0.0.1" };
  nodeReq.socket = nodeReq.connection;
  nodeReq.getHeader = (k) => headers[k.toLowerCase()];
  nodeReq.headersDistinct = headers;
  return { nodeReq, url };
}

export default async function handler(request) {
  const app = await getApp();
  const { nodeReq } = await webRequestToNode(request);

  const res = new ResponseBuffer();
  installExpressHelpers(res);

  const done = new Promise((resolve) => {
    res._resolvePromise = resolve;
  });

  try {
    // Express's app.handle dispatches through the middleware stack.
    app.handle(nodeReq, res, (err) => {
      if (err) {
        console.error("[api] handler error:", err?.message ?? err);
        if (!res.headersSent) {
          res.statusCode = 500;
          res.setHeader("Content-Type", "application/json; charset=utf-8");
          res.write(JSON.stringify({ error: "internal", message: err?.message ?? String(err) }));
        }
        res._finish();
      }
    });
  } catch (err) {
    console.error("[api] dispatch error:", err?.message ?? err);
    if (!res.headersSent) {
      res.statusCode = 500;
      res.setHeader("Content-Type", "application/json");
      res.write(JSON.stringify({ error: "internal", message: err?.message ?? String(err) }));
    }
    res._finish();
  }

  await done;

  // Serialize the buffered response back into a Web Response.
  const body = Buffer.concat(res.bodyChunks);
  const outHeaders = new Headers();
  for (const [k, v] of res.headers.entries()) {
    // Express may set multi-value headers as arrays
    for (const one of v) outHeaders.append(k, one);
  }
  // CORS: Vercel already injects this for functions, but make sure.
  if (!outHeaders.has("access-control-allow-origin")) {
    outHeaders.set("access-control-allow-origin", "*");
  }
  return new Response(body, {
    status: res.statusCode,
    statusText: res.statusMessage,
    headers: outHeaders,
  });
}

// Vercel config — Node.js serverless function (not edge). We need fs/yahoo-
// finance2 which aren't available in the edge runtime. Vercel accepts
// `nodejs` (resolves to the project's pinned Node version) or the explicit
// "nodejs20.x" / "nodejs22.x" form. Use the bare `nodejs` value to avoid
// a build-time rejection on older CLI versions.
export const config = {
  runtime: "nodejs",
  maxDuration: 30,
};
